// const pods = [
const pods = {
	'513219JDXABA002EA000092': {
		title: 'Eclectic Gold Jhumkas',
		description: 'Stunning Jhumkas with Beaded and Paisley Patterns set in 22 Karat Yellow Gold',
		prodInfo: {
			purity: 22.0,
			brand: 'Tanishq',
			gender: 'Women',
			metal: 'Gold',
			jewelleryType: 'Plain Gold Jewellery',
			product: 'Earrings',
			collection: 'Aarambh',
			metalColor: 'Yellow',
			type: 'Jhumka',
			occassion: 'Traditional Wear',
		},
		images: [
			'https://staticimg.titan.co.in/Tanishq/Catalog/513219JDXABA00_1.jpg',
			'https://staticimg.titan.co.in/Tanishq/Catalog/513219JDXABA00_2.jpg',
		],
		lastUpdatedOn: '13-09-2020',
		productId: '513219JDXABA002EA000092',
		price: {
			weight: 54,
			makingCharges: 10,
			wastage: 20,
			discountPercentage: 40,
			total: 110430.0,
		},
		offers: {
			name: 'Gandhi Jayanthi Sale',
			discountPercentage: 40,
		},
		dimensions: {
			length: 10,
			height: 20,
		},
		delivery: 12,
	},
	'513219JDKABA002EB000065': {
		title: 'Majestic Gold Jhumkas',
		description: 'Graceful Jhumkas Inspired by Traditional Artistry set in 22 Karat Yellow Gold',
		prodInfo: {
			purity: 22.0,
			brand: 'Tanishq',
			gender: 'Women',
			metal: 'Gold',
			jewelleryType: 'Plain Gold Jewellery',
			product: 'Earrings',
			collection: 'Aarambh',
			metalColor: 'Yellow',
			type: 'Jhumka',
			occassion: 'Traditional Wear',
		},
		images: [
			'https://staticimg.titan.co.in/Tanishq/Catalog/513219JDKABA00_1.jpg',
			'https://staticimg.titan.co.in/Tanishq/Catalog/513219JDKABA00_2.jpg',
		],
		lastUpdatedOn: '13-09-2020',
		productId: '513219JDKABA002EB000065',
		price: {
			weight: 54,
			makingCharges: 10,
			wastage: 20,
			discountPercentage: 40,
			total: 76248.0,
		},
		offers: {
			name: 'Clearance Sale',
			discountPercentage: 20,
		},
		dimensions: {
			length: 10,
			height: 20,
		},
		delivery: 12,
	},
	'513817DEWABAP32BA805509': {
		title: 'Artistic Gold Drop Earrings',
		description: 'Teardrop and Floral Drop Earrings with Kundan Stones set in 22 Karat Yellow Gold',
		prodInfo: {
			purity: 22.0,
			brand: 'Tanishq',
			gender: 'Women',
			metal: 'Gold',
			jewelleryType: 'Plain Jewellery with Stones',
			product: 'Earrings',
			collection: 'Padmaavat',
			metalColor: 'Yellow',
			type: 'Drops',
			occassion: 'Traditional Wear',
		},
		images: ['https://staticimg.titan.co.in/Tanishq/Catalog/513817DEWABAP3_1.jpg'],
		lastUpdatedOn: '12-02-2018',
		productId: '513817DEWABAP32BA805509',
		price: {
			weight: 13.062,
			makingCharges: 2,
			wastage: 2,
			discountPercentage: 12,
			total: 100875.0,
		},
		offers: {
			name: 'Clearance Sale',
			discountPercentage: 20,
		},
		dimensions: {
			length: 10,
			height: 20,
		},
		delivery: 12,
	},
	'511518JCZABA002EA005412': {
		title: '22 Karat Gold Jhumkas',
		description: 'Tanishq 22 Karat Gold Jhumkas',
		prodInfo: {
			purity: 22.0,
			brand: 'Tanishq',
			gender: 'Women',
			metal: 'Gold',
			jewelleryType: 'Plain Gold Jewellery',
			product: 'Earrings',
			collection: 'Bestsellers',
			metalColor: 'Yellow',
			type: 'Jhumka',
			occassion: 'Traditional Wear',
		},
		images: [
			'https://staticimg.titan.co.in/Tanishq/Catalog/511518JCZABA00_1.jpg',
			'https://staticimg.titan.co.in/Tanishq/Catalog/511518JCZABA00_2.jpg',
			'https://staticimg.titan.co.in/Tanishq/Catalog/511518JCZABA00_3.jpg',
			'https://staticimg.titan.co.in/Tanishq/Catalog/511518JCZABA00_4.jpg',
		],
		lastUpdatedOn: '13-09-2020',
		productId: '511518JCZABA002EA005412',
		price: {
			weight: 54,
			makingCharges: 10,
			wastage: 20,
			discountPercentage: 40,
			total: 40167.0,
		},
		offers: {
			name: 'Making Charges',
			discountPercentage: 20,
		},
		dimensions: {
			length: 10,
			height: 20,
		},
		delivery: 2,
	},
	'512016JEYABAP3': {
		title: '22 Karat Gold and Kundan Glass Jhumkas',
		description: 'Tanishq 22 Karat Gold and Kundan Glass Jhumkas',
		prodInfo: {
			purity: 22.0,
			brand: 'Tanishq',
			gender: 'Women',
			metal: 'Gold',
			jewelleryType: 'Plain Jewellery with Stones',
			product: 'Earrings',
			collection: 'Bestsellers',
			metalColor: 'Yellow',
			type: 'Jhumka',
			occassion: 'Traditional Wear',
		},
		images: [
			'https://staticimg.titan.co.in/Tanishq/Catalog/512016JEYABAP3_1.jpg',
			'https://staticimg.titan.co.in/Tanishq/Catalog/512016JEYABAP3_2.jpg',
		],
		lastUpdatedOn: '13-01-2019',
		productId: '512016JEYABAP3',
		price: {
			weight: 54,
			makingCharges: 10,
			wastage: 20,
			discountPercentage: 40,
			total: 46248.0,
		},
		offers: {
			name: 'Clearance Sale',
			discountPercentage: 20,
		},
		dimensions: {
			length: 10,
			height: 20,
		},
		delivery: 12,
	},
	'513319JDFABA182BA000003': {
		title: 'Elengant Ruby Jhumkas',
		description: 'Stunning Jhumkas Studded with Rubies and set in 22 Karat Yellow Gold',
		prodInfo: {
			purity: 22.0,
			brand: 'Tanishq',
			gender: 'Women',
			metal: 'Gold',
			jewelleryType: 'Plain Gold Jewellery',
			product: 'Earrings',
			collection: 'Aarambh',
			metalColor: 'Yellow',
			type: 'Jhumka',
			occassion: 'Traditional Wear',
		},
		images: [
			'https://staticimg.titan.co.in/Tanishq/Catalog/513319JDFABA18_1.jpg',
			'https://staticimg.titan.co.in/Tanishq/Catalog/513319JDFABA18_2.jpg',
		],
		lastUpdatedOn: '13-09-2020',
		productId: '513319JDFABA182BA000003',
		price: {
			weight: 14.86,
			makingCharges: 3,
			wastage: 12,
			discountPercentage: 10,
			total: 114324.0,
		},
		offers: {
			name: 'Clearance Sale',
			discountPercentage: 20,
		},
		dimensions: {
			length: 10,
			height: 20,
		},
		delivery: 7,
	},
	'512815JCHABA002EA005157': {
		title: '22 Karat Gold Jhumkas',
		description: 'Tanishq 22 Karat Gold Jhumkas',
		prodInfo: {
			purity: 22.0,
			brand: 'Tanishq',
			gender: 'Women',
			metal: 'Gold',
			jewelleryType: 'Plain Gold Jewellery',
			product: 'Earrings',
			collection: 'Bestsellers',
			metalColor: 'Yellow',
			type: 'Jhumka',
			occassion: 'Traditional Wear',
		},
		images: [
			'https://staticimg.titan.co.in/Tanishq/Catalog/512815JCHABA00_1.jpg',
			'https://staticimg.titan.co.in/Tanishq/Catalog/512815JCHABA00_2.jpg',
		],
		lastUpdatedOn: '13-09-2020',
		productId: '512815JCHABA002EA005157',
		price: {
			weight: 18.171,
			makingCharges: 12,
			wastage: 2,
			discountPercentage: 10,
			total: 125753.0,
		},
		offers: {
			name: 'Clearance Sale',
			discountPercentage: 20,
		},
		dimensions: {
			length: 10,
			height: 20,
		},
		delivery: 12,
	},
	'512814DPGABA402BA000387': {
		title: 'Netra Traditional Drop Earrings',
		description: 'Elegant Drop Earrings set in 22 Karat Yellow Gold and studded with Emeralds and Rubies',
		prodInfo: {
			purity: 22.0,
			brand: 'Tanishq',
			gender: 'Women',
			metal: 'Gold',
			jewelleryType: 'Jewellery with Gemstones',
			product: 'Earrings',
			collection: 'Bestsellers',
			metalColor: 'Yellow',
			type: 'Drops',
			occassion: 'Traditional Wear',
		},
		images: [
			'https://staticimg.titan.co.in/Tanishq/Catalog/512814DPGABA40_1.jpg',
			'https://staticimg.titan.co.in/Tanishq/Catalog/512814DPGABA40_2.jpg',
		],
		lastUpdatedOn: '13-09-2020',
		productId: '512814DPGABA402BA000387',
		price: {
			weight: 5.345,
			makingCharges: 1,
			wastage: 20,
			discountPercentage: 40,
			total: 125753.0,
		},
		offers: {
			name: 'Clearance Sale',
			discountPercentage: 20,
		},
		dimensions: {
			length: 10,
			height: 20,
		},
		delivery: 12,
	},
	'502015DZFABA182BA801765': {
		title: 'Sumaira Ruby Drop Earrings',
		description: 'Traditional Jhumka inspired drop earrings set in 18 Karat Yellow Gold and studded with Rubies',
		prodInfo: {
			purity: 18.0,
			brand: 'Tanishq',
			gender: 'Women',
			metal: 'Gold',
			jewelleryType: 'Jewellery with Gemstones',
			product: 'Earrings',
			collection: 'Mangalam',
			metalColor: 'Yellow',
			type: 'Jhumka',
			occassion: 'Traditional Wear',
		},
		images: [
			'https://staticimg.titan.co.in/Tanishq/Catalog/502015DZFABA18_1.jpg',
			'https://staticimg.titan.co.in/Tanishq/Catalog/502015DZFABA18_2.jpg',
		],
		lastUpdatedOn: '13-09-2020',
		productId: '502015DZFABA182BA801765',
		price: {
			weight: 4.625,
			makingCharges: 10,
			wastage: 20,
			discountPercentage: 40,
			total: 70085.0,
		},
		offers: {
			name: 'Clearance Sale',
			discountPercentage: 20,
		},
		dimensions: {
			length: 10,
			height: 20,
		},
		delivery: 12,
	},
	'5138172DQABA002EA006042': {
		title: 'Impressive Gold Neckwear Set for the Indian Bride',
		description: 'Chandbali Style Neckwear and Earrings Set crafted in 22 Karat Yellow Gold',
		prodInfo: {
			purity: 22.0,
			brand: 'Tanishq',
			gender: 'Women',
			metal: 'Gold',
			jewelleryType: 'Plain Gold Jewellery',
			product: 'Neckwear Set',
			collection: 'Shagun',
			metalColor: 'Yellow',
			type: 'Indian Bridal Neckwear Set',
			occassion: 'Bridal Wear',
		},
		images: [
			'https://staticimg.titan.co.in/Tanishq/Catalog/5138172DQABA00_1.jpg',
			'https://staticimg.titan.co.in/Tanishq/Catalog/5138172DQABA00_2.jpg',
			'https://staticimg.titan.co.in/Tanishq/Catalog/5138172DQABA00_3.jpg',
		],
		lastUpdatedOn: '11-09-2020',
		productId: '5138172DQABA002EA006042',
		price: {
			weight: 123.603,
			makingCharges: 10,
			wastage: 20,
			discountPercentage: 40,
			total: 865197.0,
		},
		offers: {
			name: 'Clearance Sale',
			discountPercentage: 10,
		},
		dimensions: {
			length: 10,
			height: 20,
		},
		delivery: 20,
	},
	'5139162COABAP32BA801186': {
		title: 'Spectacular Gold Neckwear Set for the Gujarati Bride',
		description: 'Floral Neckwear and Earrings Set with Kundan Stones crafted in 22 Karat Yellow Gold',
		prodInfo: {
			purity: 22.0,
			brand: 'Tanishq',
			gender: 'Women',
			metal: 'Gold',
			jewelleryType: 'Plain Jewellery with Stones',
			product: 'Neckwear Set',
			collection: 'Shagun',
			metalColor: 'Yellow',
			type: 'Gujarati Neckwear Set',
			occassion: 'Bridal Wear',
		},
		images: [
			'https://staticimg.titan.co.in/Tanishq/Catalog/5139162COABAP3_1.jpg',
			'https://staticimg.titan.co.in/Tanishq/Catalog/5139162COABAP3_2.jpg',
			'https://staticimg.titan.co.in/Tanishq/Catalog/5139162COABAP3_3.jpg',
		],
		lastUpdatedOn: '13-09-2020',
		productId: '5139162COABAP32BA801186',
		price: {
			weight: 85.958,
			makingCharges: 10,
			wastage: 20,
			discountPercentage: 40,
			total: 593500.0,
		},
		offers: {
			name: 'Clearance Sale',
			discountPercentage: 20,
		},
		dimensions: {
			length: 10,
			height: 20,
		},
		delivery: 12,
	},
	'5121132VMABA002EA006167': {
		title: 'Luminous Gold Neckwear Set',
		description: 'Traditional Floral Neckwear and Earrings Set Crafted in 22 Karat Yellow Gold',
		prodInfo: {
			purity: 22.0,
			brand: 'Tanishq',
			gender: 'Women',
			metal: 'Gold',
			jewelleryType: 'Plain Gold Jewellery',
			product: 'Neckwear Set',
			collection: 'Shagun',
			metalColor: 'Yellow',
			type: 'Gujarati Neckwear Set',
			occassion: 'Traditional Wear',
		},
		images: [
			'https://staticimg.titan.co.in/Tanishq/Catalog/5121132VMABA00_1.jpg',
			'https://staticimg.titan.co.in/Tanishq/Catalog/5121132VMABA00_2.jpg',
			'https://staticimg.titan.co.in/Tanishq/Catalog/5121132VMABA00_3.jpg',
		],
		lastUpdatedOn: '13-03-2020',
		productId: '5121132VMABA002EA006167',
		price: {
			weight: 17.311,
			makingCharges: 12,
			wastage: 24,
			discountPercentage: 12,
			total: 119345.0,
		},
		offers: {
			name: 'Clearance Sale',
			discountPercentage: 20,
		},
		dimensions: {
			length: 10,
			height: 20,
		},
		delivery: 23,
	},
	// ];
};

module.exports = pods;
